# Employees: Silver -> Gold

Keep only the columns downstream consumers need.

In [1]:
%run ../00_config.ipynb

/usr/local/lib/python3.12/site-packages/nbformat/validator.py:434: MissingIDFieldWarning: Cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  _validate(nbdict, ref, version, version_minor, relax_add_props)

[08/23/26 15:06:01] INFO     Using                                                                  ]8;id=12674127;file:///usr/local/lib/python3.12/site-packages/kedro/framework/project/__init__.py\__init__.py]8;;\:]8;id=12674128;file:///usr/local/lib/python3.12/site-packages/kedro/framework/project/__init__.py#302\302]8;;\
                             '/usr/local/lib/python3.12/site-packages/kedro/framework/project/rich_
                             logging.yml' as logging configuration.

[08/23/26 15:06:01] WARNING  /usr/local/lib/python3.12/site-packages/kedro/framework/context/contex ]8;id=12674135;file:///usr/local/lib/python3.12/warnings.py\warnings.py]8;;\:]8;id=12674136;file:///usr/local/lib/python3.12/warnings.py#112\112]8;;\
                             t.py:221: UserWarning: Parameters not found in your Kedro project
                             config.
                             No files of YAML or JSON format found in /app/conf/base or
                             /app/conf/local matching the glob pattern(s): ['parameters*',
                             'parameters*/**', '**/parameters*']
                               warn(f"Parameters not found in your Kedro project config.\n{exc!s}")

                    INFO     No typed parameter requirements found, returning original   ]8;id=12674143;file:///usr/local/lib/python3.12/site-packages/kedro/validation/parameter_validator.py\parameter_validator.py]8;;\:]8;id=12674144;file:///usr/local/lib/python3.12/site-packages/kedro/validation/parameter_validator.py#124\124]8;;\
                             parameters

Kedro context loaded from /app
Catalog datasets: ['raw_employees', 'bronze_employees', 'silver_employees', 'gold_employees', 'raw_sales', 'bronze_sales', 'silver_sales', 'gold_sales', 'raw_inventory', 'bronze_inventory', 'silver_inventory', 'gold_inventory', 'parameters']

In [2]:
silver_employees = catalog.load("silver_employees")
silver_employees

                    INFO     Loading data from silver_employees (CSVDataset)...                ]8;id=12674151;file:///usr/local/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=12674152;file:///usr/local/lib/python3.12/site-packages/kedro/io/data_catalog.py#1050\1050]8;;\

   employee_id      full_name   department  salary   hire_date internal_notes
0          101  Alice Johnson  engineering   95000  2021-03-15  top performer
1          102      Bob Smith        sales   72000  2020-07-01            NaN
2          103     Carla Diaz  engineering   88000  2022-01-10         remote
3          104      David Lee    marketing   68000  2023-11-20            NaN

In [3]:
gold_employees = silver_employees[EMPLOYEES_GOLD_COLUMNS]
gold_employees

   employee_id      full_name   department  salary   hire_date
0          101  Alice Johnson  engineering   95000  2021-03-15
1          102      Bob Smith        sales   72000  2020-07-01
2          103     Carla Diaz  engineering   88000  2022-01-10
3          104      David Lee    marketing   68000  2023-11-20

In [4]:
catalog.save("gold_employees", gold_employees)

                    INFO     Saving data to gold_employees (CSVDataset)...                     ]8;id=12674158;file:///usr/local/lib/python3.12/site-packages/kedro/io/data_catalog.py\data_catalog.py]8;;\:]8;id=12674159;file:///usr/local/lib/python3.12/site-packages/kedro/io/data_catalog.py#1006\1006]8;;\

## PySpark alternative (reference only)

PySpark isn't installed in this image. Left commented out to show how this
stage would select/write with Spark instead of pandas.

In [5]:
# silver_employees_spark = (
#     spark.read.option("header", "true")
#     .csv(str(PROJECT_ROOT / "data/03_silver/employees.csv"))
# )
#
# gold_employees_spark = silver_employees_spark.select(*EMPLOYEES_GOLD_COLUMNS)
#
# gold_employees_spark.write.mode("overwrite").option("header", "true").csv(
#     str(PROJECT_ROOT / "data/04_gold/employees.csv")
# )